/*
 * IQEngine Plugins Open Interface API
 *
 * The plugins API is a unified open interface for managing the processing of RF recordings and corresponding dataflow, with the goal of standardizing inputs and outputs to RF processing functions for easy of interoperability and to combat vendor lockin. The plugins API is planned to be converted to an OpenAPI spec once its further refined.  It will use JSON for the fields. 
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct FunctionNameGet200Response {
    #[serde(rename = "max_inputs", skip_serializing_if = "Option::is_none")]
    pub max_inputs: Option<i32>,
    #[serde(rename = "max_outputs", skip_serializing_if = "Option::is_none")]
    pub max_outputs: Option<i32>,
    #[serde(rename = "custom_params")]
    pub custom_params: ::std::collections::HashMap<String, crate::models::FunctionNameGet200ResponseCustomParamsValue>,
}

impl FunctionNameGet200Response {
    pub fn new(custom_params: ::std::collections::HashMap<String, crate::models::FunctionNameGet200ResponseCustomParamsValue>) -> FunctionNameGet200Response {
        FunctionNameGet200Response {
            max_inputs: None,
            max_outputs: None,
            custom_params,
        }
    }
}


