/*
 * IQEngine Plugins Open Interface API
 *
 * The plugins API is a unified open interface for managing the processing of RF recordings and corresponding dataflow, with the goal of standardizing inputs and outputs to RF processing functions for easy of interoperability and to combat vendor lockin. The plugins API is planned to be converted to an OpenAPI spec once its further refined.  It will use JSON for the fields. 
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct FunctionNameGet200ResponseCustomParamsValue {
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<Box<crate::models::FunctionNameGet200ResponseCustomParamsValueType>>,
}

impl FunctionNameGet200ResponseCustomParamsValue {
    pub fn new() -> FunctionNameGet200ResponseCustomParamsValue {
        FunctionNameGet200ResponseCustomParamsValue {
            title: None,
            r#type: None,
        }
    }
}


