/*
 * IQEngine Plugins Open Interface API
 *
 * The plugins API is a unified open interface for managing the processing of RF recordings and corresponding dataflow, with the goal of standardizing inputs and outputs to RF processing functions for easy of interoperability and to combat vendor lockin. The plugins API is planned to be converted to an OpenAPI spec once its further refined.  It will use JSON for the fields.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct FunctionNamePostRequest {
    #[serde(rename = "samples_b64", skip_serializing_if = "Option::is_none")]
    pub samples_b64: Option<Vec<crate::models::SamplesB64>>,
    #[serde(rename = "samples_cloud", skip_serializing_if = "Option::is_none")]
    pub samples_cloud: Option<Vec<crate::models::SamplesCloud>>,
    #[serde(
        rename = "additionalProperties",
        skip_serializing_if = "Option::is_none"
    )]
    pub additional_properties:
        Option<Box<crate::models::FunctionNameGet200ResponseCustomParamsValueType>>,
}

impl FunctionNamePostRequest {
    pub fn new() -> FunctionNamePostRequest {
        FunctionNamePostRequest {
            samples_b64: None,
            samples_cloud: None,
            additional_properties: None,
        }
    }
}
