/*
 * IQEngine Plugins Open Interface API
 *
 * The plugins API is a unified open interface for managing the processing of RF recordings and corresponding dataflow, with the goal of standardizing inputs and outputs to RF processing functions for easy of interoperability and to combat vendor lockin. The plugins API is planned to be converted to an OpenAPI spec once its further refined.  It will use JSON for the fields.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SamplesCloud {
    #[serde(rename = "account_name")]
    pub account_name: String,
    #[serde(rename = "container_name")]
    pub container_name: String,
    #[serde(rename = "file_path")]
    pub file_path: String,
    #[serde(rename = "sas_token", skip_serializing_if = "Option::is_none")]
    pub sas_token: Option<String>,
    #[serde(rename = "byte_offset", skip_serializing_if = "Option::is_none")]
    pub byte_offset: Option<i32>,
    #[serde(rename = "byte_length", skip_serializing_if = "Option::is_none")]
    pub byte_length: Option<i32>,
    #[serde(rename = "data_type")]
    pub data_type: crate::models::DataType,
    #[serde(rename = "sample_rate", skip_serializing_if = "Option::is_none")]
    pub sample_rate: Option<f32>,
    #[serde(rename = "center_freq", skip_serializing_if = "Option::is_none")]
    pub center_freq: Option<f32>,
}

impl SamplesCloud {
    pub fn new(
        account_name: String,
        container_name: String,
        file_path: String,
        data_type: crate::models::DataType,
    ) -> SamplesCloud {
        SamplesCloud {
            account_name,
            container_name,
            file_path,
            sas_token: None,
            byte_offset: None,
            byte_length: None,
            data_type,
            sample_rate: None,
            center_freq: None,
        }
    }
}
