/*
 * IQEngine Plugins Open Interface API
 *
 * The plugins API is a unified open interface for managing the processing of RF recordings and corresponding dataflow, with the goal of standardizing inputs and outputs to RF processing functions for easy of interoperability and to combat vendor lockin. The plugins API is planned to be converted to an OpenAPI spec once its further refined.  It will use JSON for the fields.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SamplesB64 {
    #[serde(rename = "samples")]
    pub samples: String,
    #[serde(rename = "data_type")]
    pub data_type: crate::models::DataType,
    #[serde(rename = "sample_rate", skip_serializing_if = "Option::is_none")]
    pub sample_rate: Option<f32>,
    #[serde(rename = "center_freq", skip_serializing_if = "Option::is_none")]
    pub center_freq: Option<f32>,
}

impl SamplesB64 {
    pub fn new(samples: String, data_type: crate::models::DataType) -> SamplesB64 {
        SamplesB64 {
            samples,
            data_type,
            sample_rate: None,
            center_freq: None,
        }
    }
}
